# Generated by Django 6.0.1 on 2026-05-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HealthOverview", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
